// Parity with the peck.to v1 client. The fixture holds the OP_RETURN scripts
// v1 produces for tips and identity profiles; it is generated by running v1's
// own code (see scripts/gen-v1-parity-fixtures.mjs), not written by hand. The
// builders must reproduce every script byte for byte, signature included: the
// wallet is a ProtoWallet with the same fixed key, and ECDSA here is
// deterministic.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { PrivateKey, ProtoWallet, Utils } from '@bsv/sdk'
import { describe, expect, it } from 'vitest'
import {
  PROTO_MAP,
  identityProfile,
  opReturnPushes,
  payment,
  signPayload,
  toLockingScript,
  verifyAip,
  verifyIdentityProfile,
  type IdentityProfileInput,
  type PaymentInput,
} from '../src/schema/index.js'

interface Fixture {
  walletKey: number
  identityKey: string
  serial: string
  payments: Array<{ note: string; input: PaymentInput; scriptHex: string }>
  profiles: Array<{ note: string; input: IdentityProfileInput; scriptHex: string }>
}

const fixture = JSON.parse(
  readFileSync(resolve(import.meta.dirname, 'fixtures/schema/v1-parity.json'), 'utf8'),
) as Fixture

const wallet = new ProtoWallet(new PrivateKey(fixture.walletKey))

describe('fixture', () => {
  it('is for the wallet these tests use', async () => {
    expect((await wallet.getPublicKey({ identityKey: true })).publicKey).toBe(fixture.identityKey)
    expect(fixture.payments.length).toBeGreaterThan(0)
    expect(fixture.profiles.length).toBeGreaterThan(0)
  })
})

describe('payment(): the same bytes as a v1 tip', () => {
  for (const c of fixture.payments) {
    it(c.note, async () => {
      const script = await signPayload(payment(c.input), { wallet })
      expect(script.toHex()).toBe(c.scriptHex)
      // The v1 script is a real signed record: the signature verifies.
      expect(verifyAip(c.scriptHex)).toMatchObject({ algorithm: 'BRC77', valid: true })
    })
  }

  it('lays out MAP SET app, type payment, tx, paymail, value, then the AIP section', () => {
    const c = fixture.payments[0]!
    const texts = opReturnPushes(c.scriptHex)!.map((b) => Utils.toUTF8(b))
    expect(texts.slice(0, 12)).toEqual([
      PROTO_MAP, 'SET', 'app', 'peck.to', 'type', 'payment',
      'tx', c.input.targetTxid, 'paymail', c.input.recipient, 'value', String(c.input.amount),
    ])
    // The separator is the one-byte push 01 7c, as in v1.
    expect(c.scriptHex).toContain('017c')
  })
})

describe('identityProfile(): the same bytes as v1 setIdentityProfile', () => {
  for (const c of fixture.profiles) {
    it(c.note, async () => {
      const profile = await identityProfile({ ...c.input, serial: fixture.serial }, { wallet })
      expect(toLockingScript(profile).toHex()).toBe(c.scriptHex)
      // Reading v1's script back gives a valid, self-signed profile.
      const check = verifyIdentityProfile(c.scriptHex)
      expect(check).toMatchObject({ identity: fixture.identityKey, valid: true })
      expect(check?.fields).toEqual(profile.fields)
    })
  }
})
