/**
 * peck-view/v1: the hydrated read model served by the overlay under /v2.
 *
 * GENERATED by scripts/sync-peck-view.mjs from the vendored contract
 * (src/read/peck-view/peck-view.schema.json). Do not edit by hand: re-run
 * `npm run sync:peck-view -- <path to the contract schema>`.
 *
 * Contract source sha256: fa01f861e3beaeca54ef3cf139d5085438cb326fa46ccb21e4f39556b6227f8d
 */

/**
 * peck-view/v1: the hydrated read model served by the overlay under /v2. The overlay (producer) owns this contract; clients and the SDK consume it. Every view is viewer-independent: nothing in a PostView, ThreadView, ProfileView or FeedPage depends on who asks, so responses can be cached by URL. Per-viewer facts (liked by me, following, blocked) live only in ViewerState. Evolution rules: within v1 the overlay may ADD optional properties and ADD enum values documented as open; it never removes, renames or retypes a property. Consumers must ignore properties they do not know. A breaking change is a new contract version (peck-view/v2) served side by side. The producer validates its own responses strictly (additionalProperties: false), so a leaked database column fails the overlay's own contract tests.
 */
export type PeckView = FeedPage | ThreadView | ProfileView | PostBatch | ViewerState | ErrorResponse
/**
 * A BRC-100 identity key: a 66-hex compressed secp256k1 public key, lowercase.
 */
export type IdentityKey = string
/**
 * A BSV transaction id: 64 lowercase hex characters.
 */
export type Txid = string
/**
 * A signing key as the chain carries it: either a base58 P2PKH address (1…) or a 66-hex compressed secp256k1 public key (02…/03…).
 */
export type Key = string

/**
 * One page of a feed (GET /v2/feed, and later search and profile feeds). There is no total count by design.
 */
export interface FeedPage {
  /**
   * The posts on this page, in feed order.
   */
  items: PostView[]
  /**
   * Cursor for the next page. Null when this is the last page.
   */
  next: FeedCursor | null
}
/**
 * One post, hydrated for rendering: author, counts, media, provenance, one level of referenced post and a stub of the parent. Viewer-independent. Produced only by hydratePosts.
 */
export interface PostView {
  /**
   * The post's transaction id (64 lowercase hex); its permanent address.
   */
  txid: string
  /**
   * Bitcoin Schema MAP type as indexed: post, reply or repost today. Open set: other values (e.g. function_response) may appear; render unknown types as a post.
   */
  type: string
  /**
   * Content kind from MAP (e.g. longform, note), lowercase. Null when unset.
   */
  kind: string | null
  /**
   * The MAP app that wrote the transaction (peck.to, twetch, treechat, …). Null when unset.
   */
  app: string | null
  author: AuthorView
  /**
   * When the post was made (the indexed timestamp), ISO 8601 in UTC with a trailing Z.
   */
  createdAt: string
  /**
   * Block the transaction was mined in. Null while unconfirmed (the index stores 0 or NULL for those).
   */
  blockHeight: number | null
  /**
   * The text body: MAP content, falling back to the B content. Null when the body is binary media (see `media`) or empty. Untrusted user input: sanitize before rendering it as markup.
   */
  text: string | null
  /**
   * B-protocol media type of the body as written on-chain (text/plain, text/markdown, image/jpeg, …). Null when unset. Use it to pick a renderer, e.g. markdown for text/markdown.
   */
  mediaType: string | null
  /**
   * True when `text` was cut to the response limit. Limits, in characters (Unicode code points): 262144 for ThreadView.post, 16384 for every other post (feeds, batches, replies, parents, embedded refs). GET /v2/post/{txid} returns the long form.
   */
  textTruncated: boolean
  /**
   * Length of the full text in characters (Unicode code points), before truncation. 0 when `text` is null.
   */
  textLength: number
  /**
   * Media carried by the transaction: the B body when its media type is image/*, audio/* or video/*, followed by every extra output (post_attachments) in vout order, whatever its type. Empty when there is none.
   */
  media: MediaItem[]
  /**
   * MAP tags, trimmed, empty ones dropped. The index stores them as one comma-joined string, so a tag that itself contains a comma arrives split.
   */
  tags: string[]
  /**
   * MAP channel (rarely used). Null when unset.
   */
  channel: string | null
  /**
   * Location attached to the post, when both lat and lng are set.
   */
  geo: Geo | null
  /**
   * The post this one replies to. Null for top-level posts.
   */
  parentTxid: Txid | null
  /**
   * The thread root as materialized by the indexer (thread_root_tx), or null. Not filled for most replies yet: walk parentTxid when you need the root.
   */
  threadRootTxid: Txid | null
  /**
   * Stub of the parent for 'Replying to'. Null exactly when parentTxid is null, and always null on an embedded `ref`.
   */
  parent: ParentStub | null
  /**
   * The post this one reposts or quotes: the indexed ref_txid; for older rows without one, a MAP quote target ({"subcontext":"quote","tx":…}) or the first twetch.com/t/<txid> link in the text.
   */
  refTxid: Txid | null
  /**
   * repost: type is repost, the post re-shares `ref` without content of its own. quote: the post has its own content and embeds `ref`. Null exactly when refTxid is null.
   */
  refKind: 'repost' | 'quote' | null
  /**
   * The referenced post, embedded one level deep: its own `ref` and `parent` are always null (its refTxid/parentTxid are kept). Null when refTxid is null or the target is not indexed; render a link to refTxid then.
   */
  ref: PostView | null
  counts: PostCounts
  provenance: Provenance
  /**
   * True when the overlay withheld text and media because the operator's paywall covers the post (text null, media empty). /v2 never unlocks content per viewer. The paywall is disabled in production, so this is false today.
   */
  paywalled: boolean
}
/**
 * Who signed a post, resolved once on the overlay. A single function produces every AuthorView, so all clients show the same name, handle and picture for the same key. Identity is keyed on keys, never on names: `key` is the on-chain signer and `identityKey` the BRC-100 identity it resolves to. Names, handles and pictures are labels that can change between reads.
 */
export interface AuthorView {
  /**
   * The key that signed the post, exactly as indexed (pecks.author): a base58 P2PKH address, or a 66-hex compressed public key for agent and BRC-100-native authors. Constant for the post. Use it as the profile fallback when `handle` and `identityKey` are null.
   */
  key: string
  /**
   * P2PKH address of `key`: equal to `key` when `key` is an address, derived from the public key otherwise. Null only when `key` is neither.
   */
  address: string | null
  /**
   * BRC-100 identity key that `key` belongs to. First match wins: (1) overlay identity resolution (key-binding, light identity attestations, ProfileToken, handle claims); (2) the identity key recorded on a legacy peck.to account for this address; (3) `key` itself when it is a public key. Null when nothing links the key to an identity. Prefer it over `key` as the person's id when present. Always null for custodial relay keys.
   */
  identityKey: IdentityKey | null
  /**
   * Canonical handle without the leading @, from on-chain claims only: light handle claims (identity_handles) > HandleToken > the ProfileToken's own handle field. Resolved on every read, so it can move to a new owner; the key cannot. Null when unclaimed, and always null for custodial relay keys.
   */
  handle: string | null
  /**
   * The name to render. Never empty. Candidates in order, first non-empty wins, and `nameSource` records which one: identity > tx > account > external > paymail > key (see nameSource). For custodial relay keys only tx, external and key are considered, because the key belongs to the app.
   */
  displayName: string
  /**
   * Where `displayName` came from. identity: the author's own on-chain profile (light identity attestation preferred over ProfileToken). tx: the display_name written into this transaction's MAP data (for custodial relays that is the app's claim about its user). account: the legacy peck.to account row (off-chain). external: an off-chain platform profile such as twetch; never written on-chain, render with a provenance marker. paymail: the local part of the account paymail. key: nothing named the author; `displayName` is the shortened key (first 6 + … + last 4).
   */
  nameSource: 'identity' | 'tx' | 'account' | 'external' | 'paymail' | 'key'
  /**
   * URL of the author's own picture, ready for an <img src>. Null when the author has no usable picture; peck-native clients then show `generatedAvatarUrl`, others a monogram. Mapping from `avatarRef`, the only place it is done: uhrp://<sha256> → <UHRP base>/uhrp/<sha256>; b://<txid> → <media base>/b/<txid> (<media base>/xavatar/<txid>, a downscaling proxy, when the picture comes from an external profile); ord://<outpoint> → <media base>/ord/<outpoint>; https:// and http:// URLs pass through; data:image/* URIs pass through; peck.to's own generated /avatar/ URLs count as no picture; anything else maps to null. The media base defaults to https://peck.to.
   */
  avatarUrl: string | null
  /**
   * The picture reference exactly as published, before mapping (uhrp://, b://, ord://, https://, data:image/…). Null when the winning record has no picture reference.
   */
  avatarRef: string | null
  /**
   * Which record the picture came from: identity (on-chain profile), account (legacy peck.to account row) or external (off-chain platform profile, b:// uploads only; other twetch picture formats are dead links). The first record whose reference maps to a URL wins, in that order. Null when `avatarUrl` is null.
   */
  avatarSource: 'identity' | 'account' | 'external' | null
  /**
   * Deterministic generated avatar (the peck bird) for this key: <media base>/avatar/<key>?seed=<address>. The seed is the P2PKH address so one key gets the same bird on every surface. Always present.
   */
  generatedAvatarUrl: string
  /**
   * Paymail on the legacy peck.to account row for this key, if any. Off-chain.
   */
  paymail: string | null
  /**
   * Set when `key` is a known shared custodial key (e.g. treechat.io): the app signed on its users' behalf, so `key` identifies the app, not the person. The value names the app. Null otherwise.
   */
  custodialRelay: string | null
  /**
   * Set when the name or the picture came from an off-chain platform profile (nameSource or avatarSource is external). Null otherwise.
   */
  external: ExternalProfileRef | null
}
/**
 * Where an off-chain name or picture came from. The binding between the account and the key lives only in that platform's database, not on-chain.
 */
export interface ExternalProfileRef {
  /**
   * The platform the profile was read from, e.g. twetch.
   */
  source: string
  /**
   * The account id on that platform, when known.
   */
  externalId: string | null
}
/**
 * One piece of binary media carried by a post's transaction.
 */
export interface MediaItem {
  /**
   * Fetchable URL: <media base>/b/<txid> for the B-protocol body, <media base>/b/<txid>?vout=<vout> for an extra output. The media base defaults to https://peck.to, whose /b/ proxy serves only sniffed raster/audio/video types from the chain.
   */
  url: string
  /**
   * Declared media type (image/jpeg, video/mp4, …) as written on-chain. Clients must not trust it for security decisions.
   */
  mediaType: string | null
  /**
   * Declared filename, if any.
   */
  filename: string | null
  /**
   * Output index for an extra output (post_attachments). Null for the post's main B body.
   */
  vout: number | null
  /**
   * Size in bytes when the index knows it; null otherwise.
   */
  sizeBytes: number | null
}
/**
 * Location the author attached to the post.
 */
export interface Geo {
  /**
   * Latitude in degrees.
   */
  lat: number
  /**
   * Longitude in degrees.
   */
  lng: number
}
/**
 * Just enough of a reply's parent to render 'Replying to <name>'. The full parent is in ThreadView.parent.
 */
export interface ParentStub {
  /**
   * The parent's txid (same as PostView.parentTxid).
   */
  txid: string
  /**
   * The parent's author. Null when the parent is not indexed.
   */
  author: AuthorView | null
}
/**
 * Aggregates about a post. All are counted live at read time except lockedSats and powBits, which the indexer materializes on the post row.
 */
export interface PostCounts {
  /**
   * Reactions targeting this post (every row in reactions, like /v1/post; not unique reactors).
   */
  likes: number
  /**
   * Direct replies: posts whose parent is this post.
   */
  replies: number
  /**
   * Posts of type repost that reference this post.
   */
  reposts: number
  /**
   * Posts of any other type that reference this post with their own content.
   */
  quotes: number
  /**
   * Satoshis paid with this post as context (sum of payments.amount where context_txid is this post).
   */
  tipSats: number
  /**
   * Satoshis locked against this post (MAP type=lock commitments), as materialized on the post row.
   */
  lockedSats: number
  /**
   * Summed difficulty bits of valid proof-of-work boosts, as materialized on the post row.
   */
  powBits: number
}
/**
 * What the chain says about who stands behind a post, graded once on the overlay.
 */
export interface Provenance {
  /**
   * Decided in this order. custodial: signed by a known shared custodial key, or app is treechat; the signer is the app, not the person (decided first because it rests on facts the index always holds). key: the Author Identity Protocol signature was verified against the author key. unverified: no verified signature on record; a statement about the index, not proof of forgery (some apps sign over preimage variants the verifier does not check).
   */
  grade: 'custodial' | 'key' | 'unverified'
  /**
   * The indexer's raw AIP verification flag (pecks.aip_verified). Null when the indexer never checked.
   */
  aipVerified: boolean | null
  /**
   * The display_name written into the transaction itself (MAP), if any. For custodial relays this is the only name the chain carries.
   */
  nameInTx: string | null
}
/**
 * Keyset position after the last item of a page, in the ecosystem's structured-cursor form (before_<sort column>=<value>). Send every key and value back unchanged as query parameters, together with the same filters, to get the next page. The keys follow the sort columns of the chosen rank (before_ts and before_txid for rank=latest), so treat them as opaque.
 */
export interface FeedCursor {
  [k: string]: string | number
}
/**
 * Response of GET /v2/post/{txid}: the requested post (`post`, text up to 262144 characters), its direct parent and every descendant reply, hydrated in one response.
 */
export interface ThreadView {
  post: PostView
  /**
   * The post it replies to, fully hydrated. Null for a top-level post or when the parent is not indexed.
   */
  parent: PostView | null
  /**
   * All descendants of `post`, level by level (children before grandchildren), oldest first within a level. Build the tree from each reply's parentTxid.
   */
  replies: PostView[]
  /**
   * True when the descendant walk stopped at its cap (500 replies or 10 levels), so `replies` is incomplete.
   */
  repliesTruncated: boolean
}
/**
 * Response of GET /v2/profile/{key|@handle}: an identity's header. `author` is baked exactly like a post author; author.key is the key the profile was looked up by (the handle owner's identity key for @handle lookups). Its posts come from GET /v2/feed?author=… (a FeedPage).
 */
export interface ProfileView {
  author: AuthorView
  /**
   * Bio from the identity profile attestation, else the ProfileToken, else the legacy account row. Untrusted user text. Null when none.
   */
  bio: string | null
  /**
   * Outpoint (<txid>.<vout>) of the canonical profile record the name and picture came from, when on-chain.
   */
  profileOutpoint: string | null
  /**
   * Every key known to sign for this identity: the identity key, its P2PKH address, and bound signing keys with their addresses. Posts authored by any of them belong to the profile.
   */
  keys: Key[]
  counts: ProfileCounts
}
/**
 * Social graph counts for a profile.
 */
export interface ProfileCounts {
  /**
   * Follow records pointing at any of the profile's keys or its handle.
   */
  followers: number
  /**
   * Follow records made by any of the profile's keys.
   */
  following: number
}
/**
 * Response of POST /v2/posts: many posts by txid in one call.
 */
export interface PostBatch {
  /**
   * The posts that were found, in request order.
   */
  posts: PostView[]
  /**
   * Requested txids that are not indexed.
   */
  missing: Txid[]
}
/**
 * Response of POST /v2/viewer/state: the only per-viewer read in /v2. Built from public on-chain records looked up by the viewer's key; never cached by the overlay.
 */
export interface ViewerState {
  /**
   * The viewer key the state was computed for, as given.
   */
  viewer: string
  /**
   * Every key treated as the viewer: the given key, its identity key, bound signing keys and their addresses.
   */
  keys: Key[]
  /**
   * State per requested txid.
   */
  posts: {
    [k: string]: PostViewerState
  }
  /**
   * State per requested author key, keyed exactly as requested.
   */
  authors: {
    [k: string]: AuthorViewerState
  }
}
/**
 * What one viewer has done to one post.
 */
export interface PostViewerState {
  /**
   * The viewer (any of ViewerState.keys) has a reaction on this post.
   */
  liked: boolean
  /**
   * The viewer has a post of type repost referencing this post.
   */
  reposted: boolean
}
/**
 * The viewer's relationship to one author.
 */
export interface AuthorViewerState {
  /**
   * The viewer has a follow record for this author (by any of its keys or its handle).
   */
  following: boolean
  /**
   * The viewer has a block record for this author.
   */
  blocked: boolean
  /**
   * The viewer has a mute record for this author.
   */
  muted: boolean
}
/**
 * Body of every non-2xx /v2 response.
 */
export interface ErrorResponse {
  error: {
    /**
     * Stable machine-readable code: bad_request, not_found, timeout (a search lane gave up; retry later) or internal.
     */
    code: string
    /**
     * Human-readable detail. Not stable; do not parse.
     */
    message: string
  }
}
