/**
 * peck-view/v1: the hydrated read model served by the overlay under /v2.
 *
 * GENERATED by scripts/sync-peck-view.mjs from the vendored contract
 * (src/read/peck-view/peck-view.schema.json). Do not edit by hand: re-run
 * `npm run sync:peck-view -- <path to the contract schema>`.
 *
 * Contract source sha256: 239622895fb0d33b1fad9200d417f2c9a30f6f05c5db73b92a4aeb47b41bff31
 */

/**
 * peck-view/v1: the hydrated read model served by the overlay under /v2. The overlay (producer) owns this contract; clients and the SDK consume it. Every view is viewer-independent: nothing in a PostView, ThreadView, ProfileView or FeedPage depends on who asks, so responses can be cached by URL. Per-viewer facts (liked by me, following, blocked) live only in ViewerState. Evolution rules: within v1 the overlay may ADD optional properties and ADD enum values documented as open; it never removes, renames or retypes a property. Consumers must ignore properties they do not know. A breaking change is a new contract version (peck-view/v2) served side by side. The producer validates its own responses strictly (additionalProperties: false), so a leaked database column fails the overlay's own contract tests. TypeScript types are generated from this schema.
 */
export type PeckView =
  | FeedPage
  | ThreadView
  | ProfileView
  | PostBatch
  | ViewerState
  | AppList
  | ReactionPage
  | SiteStats
  | ChannelList
  | IdentityList
  | LensList
  | ErrorResponse
/**
 * A BRC-100 identity key: a 66-hex compressed secp256k1 public key, lowercase.
 */
export type IdentityKey = string
/**
 * A BSV transaction id: 64 lowercase hex characters.
 */
export type Txid = string
/**
 * A signing key as the chain carries it: either a base58 P2PKH address (1…) or a 66-hex compressed secp256k1 public key (02…/03…).
 */
export type Key = string
/**
 * The name of a channel. Channels are an open namespace: nobody owns a name, and a channel exists as soon as a post or message names it. Case-sensitive and matched exactly (GET /v2/feed?channel= takes the same value). Letters, digits, dots, dashes and underscores, starting with a letter or digit, at most 64 characters, so a name is safe in a URL path segment. Names that do not fit are never listed.
 */
export type ChannelName = string

/**
 * One page of a feed (GET /v2/feed, and later search and profile feeds). There is no total count by design.
 */
export interface FeedPage {
  /**
   * The posts on this page, in feed order.
   */
  items: PostView[]
  /**
   * Cursor for the next page. Null when this is the last page.
   */
  next: FeedCursor | null
}
/**
 * One post, hydrated for rendering: author, counts, media, provenance, one level of referenced post and a stub of the parent. Viewer-independent. Every PostView comes from the same hydration step, whether it is served in a feed, a thread or a batch.
 */
export interface PostView {
  /**
   * The post's transaction id (64 lowercase hex); its permanent address.
   */
  txid: string
  /**
   * Bitcoin Schema MAP type as indexed: post, reply or repost today. Open set: other values (e.g. function_response) may appear; render unknown types as a post. Posts carried by another protocol (see `source`) use post, reply and vote; a vote has no text of its own, and source.vote names its target. A location never changes the type: a pin is a post (or reply, or repost) whose `geo` is set, and a pin written with the legacy MAP type pin is served as type post with kind pin. object is a located object that is not a post (a place registered by an app such as locus): it always has `geo`, usually has no text, and a text feed can leave it out by asking for types=post,reply,repost.
   */
  type: string
  /**
   * Content kind from MAP (e.g. longform, note), lowercase. Null when unset. pin marks a post written with the legacy MAP type pin (peck.world before June 2026); it renders exactly like any other post with a location. Never filter pins by kind: most pins have no kind, and `geo` is what makes a post a pin.
   */
  kind: string | null
  /**
   * The MAP app that wrote the transaction (peck.to, twetch, treechat, …), or zanaadu for Zanaadu posts, replies and votes (see `source`). Null when unset.
   */
  app: string | null
  author: AuthorView
  /**
   * When the post was made (the indexed timestamp), ISO 8601 in UTC with a trailing Z.
   */
  createdAt: string
  /**
   * Block the transaction was mined in. Null while unconfirmed (the index stores 0 or NULL for those).
   */
  blockHeight: number | null
  /**
   * The text body: MAP content, falling back to the B content. Null when the body is binary media (see `media`) or empty. Untrusted user input: sanitize before rendering it as markup.
   */
  text: string | null
  /**
   * B-protocol media type of the body as written on-chain (text/plain, text/markdown, image/jpeg, …). Null when unset. Use it to pick a renderer, e.g. markdown for text/markdown.
   */
  mediaType: string | null
  /**
   * True when `text` was cut to the response limit. Limits, in characters (Unicode code points): 262144 for ThreadView.post, 16384 for every other post (feeds, batches, replies, parents, embedded refs). GET /v2/post/{txid} returns the long form.
   */
  textTruncated: boolean
  /**
   * Length of the full text in characters (Unicode code points), before truncation. 0 when `text` is null.
   */
  textLength: number
  /**
   * Media carried by the transaction: the B body when its media type is image/*, audio/* or video/*, followed by every extra output the index holds for the transaction, in vout order, whatever its type. Empty when there is none.
   */
  media: MediaItem[]
  /**
   * MAP tags, trimmed, empty ones dropped. The index stores them as one comma-joined string, so a tag that itself contains a comma arrives split.
   */
  tags: string[]
  /**
   * MAP channel (rarely used). Null when unset.
   */
  channel: string | null
  /**
   * Location attached to the post: set when the transaction carries a MAP lat and lng in range. (0, 0) counts as no location. Every app reads the same field, so a location written by one app (peck.to, peck.world, …) shows in all of them. Null when the post has none.
   */
  geo: Geo | null
  /**
   * The post this one replies to. Null for top-level posts.
   */
  parentTxid: Txid | null
  /**
   * The thread root as materialized by the indexer, or null. Not filled for most replies yet: walk parentTxid when you need the root.
   */
  threadRootTxid: Txid | null
  /**
   * Stub of the parent for 'Replying to'. Null exactly when parentTxid is null, and always null on an embedded `ref`.
   */
  parent: ParentStub | null
  /**
   * The post this one reposts or quotes: the indexed reference; for older posts without one, a MAP quote target ({"subcontext":"quote","tx":…}) or the first twetch.com/t/<txid> link in the text.
   */
  refTxid: Txid | null
  /**
   * repost: type is repost, the post re-shares `ref` without content of its own. quote: the post has its own content and embeds `ref`. Null exactly when refTxid is null.
   */
  refKind: 'repost' | 'quote' | null
  /**
   * The referenced post, embedded one level deep: its own `ref` and `parent` are always null (its refTxid/parentTxid are kept). Null when refTxid is null or the target is not indexed; render a link to refTxid then.
   */
  ref: PostView | null
  counts: PostCounts
  provenance: Provenance
  /**
   * True when the overlay withheld text and media because the operator's paywall covers the post (text null, media empty). /v2 never unlocks content per viewer. The paywall is disabled in production, so this is false today.
   */
  paywalled: boolean
  source?: PostSource
}
/**
 * Who signed a post, resolved once on the overlay. Every AuthorView comes from the same resolution, so all clients show the same name, handle and picture for the same key. Identity is keyed on keys, never on names: `key` is the on-chain signer and `identityKey` the BRC-100 identity it resolves to. Names, handles and pictures are labels that can change between reads.
 */
export interface AuthorView {
  /**
   * The key that signed the post, exactly as indexed: a base58 P2PKH address, or a 66-hex compressed public key for agent and BRC-100-native authors. Constant for the post. Use it as the profile fallback when `handle` and `identityKey` are null.
   */
  key: string
  /**
   * P2PKH address of `key`: equal to `key` when `key` is an address, derived from the public key otherwise. Null only when `key` is neither.
   */
  address: string | null
  /**
   * BRC-100 identity key that `key` belongs to. First match wins: (1) overlay identity resolution (key-binding, light identity attestations, ProfileToken, handle claims); (2) the identity key recorded on a legacy peck.to account for this address; (3) `key` itself when it is a public key. Null when nothing links the key to an identity. Prefer it over `key` as the person's id when present. Always null for custodial relay keys.
   */
  identityKey: IdentityKey | null
  /**
   * Canonical handle without the leading @, from on-chain claims only: light handle claims > HandleToken > the ProfileToken's own handle field. Resolved on every read, so it can move to a new owner; the key cannot. Null when unclaimed, and always null for custodial relay keys.
   */
  handle: string | null
  /**
   * The name to render. Never empty. Candidates in order, first non-empty wins, and `nameSource` records which one: identity > tx > account > external > paymail > key (see nameSource). For custodial relay keys only tx, external and key are considered, because the key belongs to the app.
   */
  displayName: string
  /**
   * Where `displayName` came from. identity: the author's own on-chain profile (light identity attestation preferred over ProfileToken). tx: the display_name written into this transaction's MAP data (for custodial relays that is the app's claim about its user). account: the legacy peck.to account row (off-chain). external: an off-chain platform profile such as twetch; never written on-chain, render with a provenance marker. paymail: the local part of the account paymail. key: nothing named the author; `displayName` is the shortened key (first 6 + … + last 4).
   */
  nameSource: 'identity' | 'tx' | 'account' | 'external' | 'paymail' | 'key'
  /**
   * URL of the author's own picture, ready for an <img src>. Null when the author has no usable picture; peck-native clients then show `generatedAvatarUrl`, others a monogram. Mapping from `avatarRef`, the only place it is done: uhrp://<sha256> → <UHRP host>/uhrp/<sha256>; b://<txid> → <media base>/b/<txid> (<media base>/xavatar/<txid>, a downscaling proxy, when the picture comes from an external profile); ord://<outpoint> → <media base>/ord/<outpoint>; https:// and http:// URLs pass through; data:image/* URIs pass through; peck.to's own generated /avatar/ URLs count as no picture; anything else maps to null. The media base and the UHRP host are set by the overlay operator; the media base is https://peck.to by default.
   */
  avatarUrl: string | null
  /**
   * The picture reference exactly as published, before mapping (uhrp://, b://, ord://, https://, data:image/…). Null when the winning record has no picture reference.
   */
  avatarRef: string | null
  /**
   * Which record the picture came from: identity (on-chain profile), account (legacy peck.to account row) or external (off-chain platform profile, b:// uploads only; other twetch picture formats are dead links). The first record whose reference maps to a URL wins, in that order. Null when `avatarUrl` is null.
   */
  avatarSource: 'identity' | 'account' | 'external' | null
  /**
   * Deterministic generated avatar (the peck bird) for this key: <media base>/avatar/<key>?seed=<address>. The seed is the P2PKH address so one key gets the same bird on every surface. Always present.
   */
  generatedAvatarUrl: string
  /**
   * Paymail on the legacy peck.to account row for this key, if any. Off-chain.
   */
  paymail: string | null
  /**
   * Set when `key` is a known shared custodial key (e.g. treechat.io): the app signed on its users' behalf, so `key` identifies the app, not the person. The value names the app. Null otherwise.
   */
  custodialRelay: string | null
  /**
   * Set when the name or the picture came from an off-chain platform profile (nameSource or avatarSource is external). Null otherwise.
   */
  external: ExternalProfileRef | null
  sourceHandle?: SourceHandle
}
/**
 * Where an off-chain name or picture came from. The binding between the account and the key lives only in that platform's database, not on-chain.
 */
export interface ExternalProfileRef {
  /**
   * The platform the profile was read from, e.g. twetch.
   */
  source: string
  /**
   * The account id on that platform, when known.
   */
  externalId: string | null
}
/**
 * An alias the key holds in another protocol's own namespace (a Zanaadu user number, @14), shown next to the key and never as a peck handle. Absent when the key holds none. Carried on the authors of Zanaadu posts and on profiles; other surfaces may leave it out. Optional within v1.
 */
export interface SourceHandle {
  /**
   * Whose namespace the alias lives in: zanaadu. Open set.
   */
  namespace: string
  /**
   * The alias as the source shows it, e.g. @14.
   */
  value: string
  /**
   * The user number itself. When the key owns several, the lowest (which one the source shows is not proven).
   */
  number: number
  /**
   * What sort of alias this is: a numbered registry entry the source lets users buy and move, not a chosen name. Open set.
   */
  kind: 'user_number'
  /**
   * Every number the key owns, ascending. Present only when it owns more than one.
   *
   * @minItems 2
   */
  numbers?: [number, number, ...number[]]
  /**
   * Whether the overlay verified the entry against the registry's merkle root. none: the number is derived from the registry's own counter, membership is not proven.
   */
  membershipProof: 'none'
}
/**
 * One piece of binary media carried by a post's transaction.
 */
export interface MediaItem {
  /**
   * Fetchable URL: <media base>/b/<txid> for the B-protocol body, <media base>/b/<txid>?vout=<vout> for an extra output. The media base defaults to https://peck.to, whose /b/ proxy serves only sniffed raster/audio/video types from the chain.
   */
  url: string
  /**
   * Declared media type (image/jpeg, video/mp4, …) as written on-chain. Clients must not trust it for security decisions.
   */
  mediaType: string | null
  /**
   * Declared filename, if any.
   */
  filename: string | null
  /**
   * Output index for an extra output. Null for the post's main B body.
   */
  vout: number | null
  /**
   * Size in bytes when the index knows it; null otherwise.
   */
  sizeBytes: number | null
}
/**
 * Where a post was placed, as the author wrote it on chain (MAP lat, lng and optionally category). The coordinates are WGS84 degrees.
 */
export interface Geo {
  /**
   * Latitude in degrees.
   */
  lat: number
  /**
   * Longitude in degrees.
   */
  lng: number
  /**
   * What kind of place this is, from MAP category, lowercase: peck.world writes general, business, event, alert, idea or photo. Open set; treat null and unknown values as general. Optional within v1: absent only from overlays that predate it.
   */
  category?: string | null
}
/**
 * Just enough of a reply's parent to render 'Replying to <name>'. The full parent is in ThreadView.parent.
 */
export interface ParentStub {
  /**
   * The parent's txid (same as PostView.parentTxid).
   */
  txid: string
  /**
   * The parent's author. Null when the parent is not indexed.
   */
  author: AuthorView | null
}
/**
 * Aggregates about a post. All are counted live at read time except lockedSats and powBits, which the indexer materializes on the post row.
 */
export interface PostCounts {
  /**
   * Reaction records targeting this post, all of them (the same number /v1/post reports): not unique reactors.
   */
  likes: number
  /**
   * Direct replies: posts whose parent is this post.
   */
  replies: number
  /**
   * Posts of type repost that reference this post.
   */
  reposts: number
  /**
   * Posts of any other type that reference this post with their own content.
   */
  quotes: number
  /**
   * Satoshis paid with this post as the payment's context, summed over every indexed payment.
   */
  tipSats: number
  /**
   * Satoshis locked against this post (MAP type=lock commitments), as materialized on the post row.
   */
  lockedSats: number
  /**
   * Summed difficulty bits of valid proof-of-work boosts, as materialized on the post row.
   */
  powBits: number
}
/**
 * What the chain says about who stands behind a post, graded once on the overlay.
 */
export interface Provenance {
  /**
   * Decided in this order. custodial: signed by a known shared custodial key, or app is treechat; the signer is the app, not the person (decided first because it rests on facts the index always holds). key: the Author Identity Protocol signature was verified against the author key. unverified: no verified signature on record; a statement about the index, not proof of forgery (some apps sign over preimage variants the verifier does not check). Posts carried by another protocol (PostView.source) are graded unverified: they carry no AIP signature, and source.commitment says what they carry instead.
   */
  grade: 'custodial' | 'key' | 'unverified'
  /**
   * The indexer's raw AIP verification flag. Null when the indexer never checked.
   */
  aipVerified: boolean | null
  /**
   * The display_name written into the transaction itself (MAP), if any. For custodial relays this is the only name the chain carries.
   */
  nameInTx: string | null
}
/**
 * Present when the post is carried by another protocol than Bitcoin Schema (today: Zanaadu). Such a post has no AIP signature, so provenance.grade is unverified and aipVerified null; its integrity is source.commitment, which is what a renderer shows instead of the AIP grade. Absent for Bitcoin Schema posts. Optional within v1.
 */
export interface PostSource {
  /**
   * The protocol that carries the post: zanaadu. Open set.
   */
  protocol: string
  /**
   * The source's own verb for the transaction, untranslated: xanapost, xanareply, xanaupvote or xanadownvote for Zanaadu. Open set.
   */
  action: string
  /**
   * The integrity commitment the transaction carries. Null when none was recorded.
   */
  commitment: ContentCommitment | null
  /**
   * The platform fee the transaction paid: the one payment that is proven on-chain (a fixed amount to a fixed address). It is what the poster paid, not what anyone earned.
   */
  feeSats: number
  /**
   * How many other outputs the transaction has that cannot be attributed to anyone (change and payments look alike). Null when not recorded.
   */
  unattributedOutputs: number | null
  /**
   * Their total in satoshis. Never a tip or an earning. Null when not recorded.
   */
  unattributedSats: number | null
  /**
   * For a vote (type vote): its direction and target. Null for posts and replies.
   */
  vote: SourceVote | null
}
/**
 * A hash the transaction commits to, and whether the overlay verified it.
 */
export interface ContentCommitment {
  /**
   * The hash function. Open set.
   */
  algorithm: 'sha256'
  /**
   * What is hashed: text, the post's full text (posts, replies); target, the target's txid (votes). Open set.
   */
  covers: 'text' | 'target'
  /**
   * The committed hash, 64 lowercase hex.
   */
  hash: string
  /**
   * True when the overlay found the commitment in the transaction and, for text, the hash of the text it serves equals it.
   */
  verified: boolean
  /**
   * Where in the transaction the commitment was found, as the source format names it. Null when not recorded.
   */
  location: string | null
}
/**
 * A vote on another post, as the source records it.
 */
export interface SourceVote {
  /**
   * Up or down, from the topic the vote was admitted to.
   */
  direction: 'up' | 'down'
  /**
   * The post voted on (open it with GET /v2/post/{txid}). Null when the source no longer holds it.
   */
  targetTxid: Txid | null
  /**
   * The amount the vote carries in its data. Its recipient cannot be proven, so it is not a payment to anyone. Null when absent.
   */
  amountSats: number | null
}
/**
 * Keyset position after the last item of a page, in the structured-cursor form before_<sort column>=<value>. Send every key and value back unchanged as query parameters, together with the same filters, to get the next page. The keys follow the sort columns of the chosen rank (before_ts and before_txid for rank=latest), so treat them as opaque.
 */
export interface FeedCursor {
  [k: string]: string | number
}
/**
 * Response of GET /v2/post/{txid}: the requested post (`post`, text up to 262144 characters), its direct parent and every descendant reply, hydrated in one response.
 */
export interface ThreadView {
  post: PostView
  /**
   * The post it replies to, fully hydrated. Null for a top-level post or when the parent is not indexed.
   */
  parent: PostView | null
  /**
   * All descendants of `post`, level by level (children before grandchildren), oldest first within a level. Build the tree from each reply's parentTxid.
   */
  replies: PostView[]
  /**
   * True when the descendant walk stopped at its cap (500 replies or 10 levels), so `replies` is incomplete.
   */
  repliesTruncated: boolean
}
/**
 * Response of GET /v2/profile/{key|@handle|name}: an identity's header. The path segment is an address, a public key, an on-chain handle (with or without @), or a legacy peck.to account name (its username, paymail, or the paymail's local part); an on-chain handle wins over an account name. `author` is baked exactly like a post author; author.key is the key the profile was looked up by (the handle owner's identity key for handle lookups, the account's address for account names). Its posts come from GET /v2/feed?author=… (a FeedPage).
 */
export interface ProfileView {
  author: AuthorView
  /**
   * Bio from the identity profile attestation, else the ProfileToken, else the legacy account row. Untrusted user text. Null when none.
   */
  bio: string | null
  /**
   * Outpoint (<txid>.<vout>) of the canonical profile record the name and picture came from, when on-chain.
   */
  profileOutpoint: string | null
  /**
   * Every key known to sign for this identity: the identity key, its P2PKH address, and bound signing keys with their addresses. Posts authored by any of them belong to the profile.
   */
  keys: Key[]
  counts: ProfileCounts
  /**
   * Verified certificates of the identity, one entry per platform and value, ordered by platform then value. Empty when the profile has no identity key or none verify. Optional within v1: absent from overlays that predate it, and from an answer that could not verify them in time (such an answer is not cacheable).
   */
  certificates?: IdentityCertificate[]
}
/**
 * Social graph counts for a profile.
 */
export interface ProfileCounts {
  /**
   * Follow records pointing at any of the profile's keys or its handle.
   */
  followers: number
  /**
   * Follow records made by any of the profile's keys.
   */
  following: number
  /**
   * Indexed posts of every type (posts, replies, reposts) signed by any of the profile's keys: what GET /v2/feed?author=<keys> pages through. Counted live. Optional within v1: absent only from overlays that predate it.
   */
  posts?: number
}
/**
 * One attribute certified for an identity (an account on a platform, an email address), with every certifier that attests it. Only certificates that were published for the identity, are issued to it, carry a valid certifier signature and are not revoked on-chain are listed. Clients decide which certifiers they trust.
 */
export interface IdentityCertificate {
  /**
   * Lowercase id of the certificate type's platform: x, discord, email, google, github, peck. Open set: unknown for a certificate type the overlay does not recognise; render unknown values generically.
   */
  platform: string
  /**
   * The certified identifier to show: the first non-empty of the certificate's userName, username, handle, name, email or sub fields, else its first non-empty field. Null when the certificate carries none. Untrusted user text.
   */
  value: string | null
  /**
   * Public keys of the certifiers whose certificates attest this platform and value, sorted, no duplicates.
   *
   * @minItems 1
   */
  certifiers: [IdentityKey, ...IdentityKey[]]
  /**
   * SHA-256 content hashes (UHRP addresses) of those certificate documents, sorted, so a client can fetch and verify them itself.
   *
   * @minItems 1
   */
  certificateHashes: [string, ...string[]]
}
/**
 * Response of POST /v2/posts: many posts by txid in one call.
 */
export interface PostBatch {
  /**
   * The posts that were found, in request order.
   */
  posts: PostView[]
  /**
   * Requested txids that are not indexed.
   */
  missing: Txid[]
}
/**
 * Response of POST /v2/viewer/state: the only per-viewer read in /v2. Built from public on-chain records looked up by the viewer's key; never cached by the overlay.
 */
export interface ViewerState {
  /**
   * The viewer key the state was computed for, as given.
   */
  viewer: string
  /**
   * Every key treated as the viewer: the given key, its identity key, bound signing keys and their addresses.
   */
  keys: Key[]
  /**
   * State per requested txid.
   */
  posts: {
    [k: string]: PostViewerState
  }
  /**
   * State per requested author key, keyed exactly as requested.
   */
  authors: {
    [k: string]: AuthorViewerState
  }
}
/**
 * What one viewer has done to one post.
 */
export interface PostViewerState {
  /**
   * The viewer (any of ViewerState.keys) has a reaction on this post.
   */
  liked: boolean
  /**
   * The viewer has a post of type repost referencing this post.
   */
  reposted: boolean
}
/**
 * The viewer's relationship to one author.
 */
export interface AuthorViewerState {
  /**
   * The viewer has a follow record for this author (by any of its keys or its handle).
   */
  following: boolean
  /**
   * The viewer has a block record for this author.
   */
  blocked: boolean
  /**
   * The viewer has a mute record for this author.
   */
  muted: boolean
}
/**
 * The apps that have written posts, most posts first (GET /v2/apps): what an app filter chip row needs. Counts are materialized, not live: they are as old as `asOf`, refreshed in the background about every 5 minutes. Counts cover exactly the posts GET /v2/feed serves and can filter on.
 */
export interface AppList {
  /**
   * Ordered by count descending, then by app name. Apps with no posts of the requested types are absent.
   */
  apps: AppCount[]
  /**
   * When these counts were taken, ISO 8601 in UTC with a trailing Z.
   */
  asOf: string
}
/**
 * How many posts one MAP app has written.
 */
export interface AppCount {
  /**
   * The MAP app name as indexed (peck.to, twetch, treechat, ...), exactly the value GET /v2/feed?app= filters on.
   */
  app: string
  /**
   * Posts of the requested types written by this app. As of AppList.asOf, not live.
   */
  count: number
}
/**
 * Response of GET /v2/post/{txid}/reactions?kind=like|repost: who liked or reposted a post, newest first, a page at a time (limit 1-100, default 50). Every like record and every repost is listed, including reactors without a usable key, so the pages add up to PostCounts.likes and PostCounts.reposts. Quotes are posts with their own text and are not listed here. An unknown or not yet indexed txid is an empty page, not an error.
 */
export interface ReactionPage {
  /**
   * The reactions on this page, newest first.
   */
  items: Reaction[]
  /**
   * Cursor for the next page, in the same structured form as FeedPage.next (before_ts with before_actor for likes, with before_txid for reposts); send it back with the same txid and kind. Null when this is the last page.
   */
  next: FeedCursor | null
}
/**
 * One like or repost of a post, and who made it.
 */
export interface Reaction {
  /**
   * like: a like record of the post. repost: a post of type repost that references it. Open set: render an unknown kind generically.
   */
  kind: 'like' | 'repost'
  /**
   * The transaction that made the reaction: the like, or the repost post (open it with GET /v2/post/{txid}). Null for likes indexed without their transaction id.
   */
  txid: Txid | null
  /**
   * When the reaction was made (the indexed timestamp), ISO 8601 in UTC with a trailing Z.
   */
  createdAt: string
  /**
   * The like's emoji as written on-chain (twetch upvotes arrive as ⬆︎). Null for reposts and for likes without one. Untrusted user text.
   */
  emoji: string | null
  /**
   * Who reacted, exactly as indexed. Usually a key (a P2PKH address or a public key); some imported likes carry only a placeholder such as unknown or scripthash:…, and then `author` is null.
   */
  actorKey: string
  /**
   * Who reacted, baked exactly like a post author, so the name, handle and picture match that person's posts. For a repost it carries the name the repost transaction gives (custodial relays name their users there). Null when actorKey is not a key.
   */
  author: AuthorView | null
}
/**
 * Response of GET /v2/stats: the site totals a sidebar shows. Both numbers are the database planner's row estimates, not counts: close to the truth on a large table, updated as the database re-analyzes it, and never exact to the post. Render them rounded (2.6M posts).
 */
export interface SiteStats {
  /**
   * Indexed posts of every type (posts, replies, reposts), estimated. 0 on a database never analyzed.
   */
  posts: number
  /**
   * Legacy peck.to accounts, estimated. On-chain identities without an account are not counted.
   */
  accounts: number
  /**
   * Always true: the numbers are estimates. Present so a client can never mistake them for counts.
   */
  estimated: true
  /**
   * When the estimates were read, ISO 8601 in UTC with a trailing Z.
   */
  asOf: string
}
/**
 * The channels people write in (GET /v2/channels), for a channel picker or a sidebar. Two lists, because the two kinds of activity differ: `posting` ranks channels by the posts written in them recently, `rooms` ranks chat rooms by their latest message. A name can be in both. Nothing here depends on the viewer, and counts are as old as `asOf`. The legacy room `global` is the global chat itself, not a room, and is never listed.
 */
export interface ChannelList {
  /**
   * Most posts first, ties by name. Empty when nothing was posted to a channel in the window.
   */
  posting: PostingChannel[]
  /**
   * Latest message first, ties by name.
   */
  rooms: ChatRoom[]
  /**
   * The start of the window `posting` counts over, ISO 8601 in UTC with a trailing Z. Currently the 30 days before `asOf`: read this field rather than assuming the length.
   */
  postingSince: string
  /**
   * When these lists were read, ISO 8601 in UTC with a trailing Z.
   */
  asOf: string
}
/**
 * A channel that posts were written in recently, and how many.
 */
export interface PostingChannel {
  channel: ChannelName
  /**
   * Posts, replies and reposts written in this channel since ChannelList.postingSince: the posts GET /v2/feed?channel= serves with types=post,reply,repost. Authors and apps the overlay operator hides from every feed are not counted. As of ChannelList.asOf.
   */
  posts: number
}
/**
 * A chat room: a channel that messages were sent to.
 */
export interface ChatRoom {
  channel: ChannelName
  /**
   * Messages sent to the room, all time. Private (direct) messages are never counted or listed. As of ChannelList.asOf.
   */
  messages: number
  /**
   * When the latest message was sent, ISO 8601 in UTC with a trailing Z. Null only when every message of the room was indexed without a time.
   */
  lastAt: string | null
}
/**
 * The identities on the overlay, newest first (GET /v2/identities): who is on peck. An identity is a BRC-100 identity key that has published a profile. A key that is bound to another identity as one of its signing keys is folded into that identity and not listed on its own. Every item is baked exactly like a post author, so the name, handle and picture match that person's posts. An identity that published no name and holds no handle carries the shortened key as displayName (nameSource key): render it as a wallet identity.
 */
export interface IdentityList {
  /**
   * At most `limit` identities. Identities with an on-chain light profile come first, the latest attested first; then those known only from a ProfileToken, the latest minted first.
   */
  items: AuthorView[]
  /**
   * How many identities the overlay lists in all, not the size of this page.
   */
  total: number
}
/**
 * The published moderation lenses (GET /v2/lenses), newest first, for a lens picker. Nothing here depends on the viewer. A lens changes only when its issuer publishes a new version.
 */
export interface LensList {
  /**
   * At most `limit` lenses, newest first.
   */
  items: Lens[]
}
/**
 * A published, subscribable moderation lens: a rule set its issuer signed and a reader can apply to their own feeds. Filtering, never deletion: the posts stay on chain and in the index, and a reader who does not subscribe still sees them. Subscribe by passing `lensId` as `lens` to GET /v2/feed. Only the current version of a lens is listed.
 */
export interface Lens {
  /**
   * The lens's stable id, the value GET /v2/feed?lens= takes. It stays the same across new versions of the lens.
   */
  lensId: string
  issuer: AuthorView
  /**
   * What the issuer says the lens is for (curated, for example). Free text chosen by the issuer.
   */
  scope: string
  /**
   * The lens's rules, in the order the issuer published them. Rules whose shape this overlay does not understand are left out, so the list can be empty.
   */
  rules: LensRule[]
  /**
   * The legal jurisdiction the issuer attached to the lens, if any.
   */
  jurisdiction: string | null
  /**
   * The issuer's serial for this version, as published. Opaque: compare it for equality, do not order by it. Null when the lens carries none.
   */
  serial: string | null
  /**
   * The on-chain output that holds this version of the lens: <txid>.<vout>.
   */
  outpoint: string
}
/**
 * One rule of a moderation lens.
 */
export interface LensRule {
  /**
   * What the rule looks at. author: `value` is a P2PKH address. txid: a post. app: an app name. category: a classification label such as spam. tag and geo are recorded but not applied by GET /v2/feed yet. Open set: ignore a rule whose match you do not know.
   */
  match: 'author' | 'txid' | 'tag' | 'app' | 'geo' | 'category'
  /**
   * What to match, in the form `match` names.
   */
  value: string
  /**
   * hide is the only action GET /v2/feed applies today; downrank and label are recorded for later. Open set: ignore a rule whose action you do not know.
   */
  action: 'hide' | 'downrank' | 'label'
  /**
   * The text a `label` rule shows. Optional, and only on rules that carry one.
   */
  label?: string
}
/**
 * Body of every non-2xx /v2 response.
 */
export interface ErrorResponse {
  error: {
    /**
     * Stable machine-readable code: bad_request, not_found, timeout (a search lane gave up; retry later) or internal.
     */
    code: string
    /**
     * Human-readable detail. Not stable; do not parse.
     */
    message: string
  }
}
